language: objective-c
osx_image: xcode7.2
cache: cocoapods
podfile: Example/Podfile
before_install:
  - bundle
  - bundle exec pod install --project-directory=Example
script:
  - bundle exec scan
  - pod lib lint --quick
